[package]
name = "inpo"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
futures-util = "0.3.31"
get_if_addrs = "0.5.3"
regex = "1.11.1"
reqwest = "0.12.9"
tokio = { version = "1.41.1", features = ["full"] }
